name: Decode CTOOL Obfuscation

on:
  push:
    paths:
      - 'CTOOL.py.txt'
  workflow_dispatch:      # cho phép chạy thủ công từ GitHub UI
  schedule:               # chạy tự động mỗi đêm (nửa đêm UTC)
    - cron: '0 0 * * *'

jobs:
  decode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install decompiler
        run: |
          pip install --upgrade pip
          pip install uncompyle6

      - name: Decode CTOOL.py.txt
        run: |
          python - << 'EOF'
          import re, base64, bz2, zlib, marshal, sys

          src = open('CTOOL.py.txt', encoding='utf-8').read()
          m = re.search(r"a85decode\(\s*b['\"](.+?)['\"]\s*\)", src, re.DOTALL)
          if not m:
              sys.exit("❌ Không tìm thấy payload")
          payload = m.group(1).encode('ascii').decode('unicode_escape').encode('ascii')
          try:
              decoded = base64.b85decode(payload)
          except:
              decoded = base64.a85decode(payload, adobe=False, ignorechars=b'\n\r\t ')
          data = bz2.decompress(decoded)
          data = zlib.decompress(data)
          code_obj = marshal.loads(data)
          with open('decoded.pyc', 'wb') as f:
              f.write(marshal.dumps(code_obj))
          EOF

      - name: Decompile to source
        run: uncompyle6 decoded.pyc > decoded_source.py

      - name: Commit decoded source
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add decoded_source.py
          git diff --quiet || git commit -m "Auto-decode CTOOL.py.txt"
          git push
