name: Decode CTOOL Obfuscation

on:
  push:
    paths:
      - 'CTOOL.py.txt'

jobs:
  decode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install decompiler
        run: |
          python -m pip install --upgrade pip
          pip install uncompyle6

      - name: Decode CTOOL.py.txt
        run: |
          python - << 'EOF'
          import re, base64, bz2, zlib, marshal

          # 1. Đọc và tách payload
          src = open('CTOOL.py.txt', encoding='utf-8').read()
          # Lấy payload giữa a85decode(b'...') (có thể multiline)
          m = re.search(r"a85decode\(b'(.+?)'\)", src, re.DOTALL)
          if not m:
              raise RuntimeError("Không tìm thấy payload")
          payload = m.group(1).replace('\\n','').encode()

          # 2. Giải mã Base85 (RFC 1924)
          data = base64.b85decode(payload)

          # 3. Giải nén BZ2 → Zlib
          data = bz2.decompress(data)
          data = zlib.decompress(data)

          # 4. Tạo code object và xuất .pyc
          code_obj = marshal.loads(data)
          with open('decoded.pyc', 'wb') as f:
              f.write(marshal.dumps(code_obj))
          EOF

      - name: Decompile to source
        run: |
          uncompyle6 decoded.pyc > decoded_source.py

      - name: Commit decoded source
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add decoded_source.py
          git diff --quiet && echo "No changes to commit" || git commit -m "Auto-decode CTOOL.py.txt"
          git push
