name: Decode Python Script

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  decode-job:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy mã nguồn từ kho chứa của bạn
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Thiết lập môi trường Python 3.8 (tương thích nhất cho marshal)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Bước 3: Chạy script giải mã
      - name: Run Decoder
        run: python decoder.py