# Tên của quy trình GitHub Actions
name: Deobfuscate Python Script

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  decode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Run deobfuscation script
        run: python decoder.py